# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies (ignore scripts to avoid unintended auth triggers)
RUN npm install --ignore-scripts

# Copy the rest of the application
COPY . .

# Expose no port because server communicates over stdio

# Set entrypoint
ENTRYPOINT ["node", "index.js"]
